# Generated by Django 4.1.7 on 2023-04-26 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='کاربر ویژه'),
        ),
    ]
