# Generated by Django 4.2.1 on 2023-05-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('page_title', models.CharField(default='جی جی کالا', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('caption', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='Sex-Toys-photo')),
                ('position', models.IntegerField(unique=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_related', to='Category.category')),
            ],
            options={
                'ordering': ['parent__id', 'position'],
            },
        ),
    ]
