# Generated by Django 4.1.7 on 2023-05-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='product_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
