# Generated by Django 4.1.7 on 2023-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sextoys',
            name='real',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
