# Generated by Django 4.2.1 on 2023-05-30 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sextoys',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits_related', to='account.viewcounter'),
        ),
        migrations.AddField(
            model_name='sextoys',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_Products', to=settings.AUTH_USER_MODEL, verbose_name='اضافه کننده'),
        ),
        migrations.AddField(
            model_name='sextoys',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='review_related', to='review.reviewmodel'),
        ),
    ]
